name: Basic Tests

on: [push]

jobs:
  basic:

    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install --frozen-lockfile
    - name: Symlink webpack
      run: |
        sudo ln -s . ./node_modules/webpack
    - name: Basic tests
      run: |
        yarn test:basic --ci
        
  lint:

    runs-on: ubuntu-latest
    env:
      CI: true

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install --frozen-lockfile
    - name: Symlink webpack
      run: |
        sudo ln -s . ./node_modules/webpack
    - name: Linting
      run: |
        yarn lint
        
  integration:

    runs-on: ${{ matrix.os }}
    needs: [basic, lint]
    env:
      CI: true

    strategy:
      matrix:
        node-version: [10.x, 12.x]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install --frozen-lockfile
    - name: Symlink webpack
      if: matrix.os == 'windows-latest'
      run: |
        mklink /D node_modules\webpack .
    - name: Symlink webpack
      if: matrix.os != 'windows-latest'
      run: |
        sudo ln -s . ./node_modules/webpack
    - name: Integration tests
      run: |
        yarn cover:integration --ci
